version: 0.2

phases:
  pre_build:
    commands:
      - echo Configuring AWS CLI
      - aws configure set default.region $AWS_DEFAULT_REGION
      - aws configure set default.aws_access_key_id $AWS_ACCESS_KEY
      - aws configure set default.aws_secret_access_key $AWS_ACCESS_KEY_SECRET   
  build:
    commands:
      - echo Build started on `date`
      - bundle update jekyll
      - bundle install
      - jekyll --version
      - jekyll b
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading to S3...
      - aws s3 sync ./_site/ s3://$AWS_S3_BUCKET/latest/ --delete --grants read=id=$AWS_CF_S3_ID --exclude '.gitignore' --exclude 'buildspec.yml' --exclude 'README.md' --exclude 'run.sh'
      - echo Invalidating CloudFront cache ...
      - aws cloudfront create-invalidation --distribution-id $AWS_CF_DIST_ID --paths '/*'
